apiVersion: v2
name: myapp
description: Helm chart to deploy myapp on Azure Kubernetes Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - myapp
  - aks
maintainers:
  - name: platform
