environment: prod

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

image:
  repository: lgexample654.azurecr.io/myapp
  pullPolicy: IfNotPresent
  tag: "prod"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  azure:
    internal: false

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  minDomains: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1
